version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: political_test/app/Dockerfile
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/political_test
    volumes:
      - ./political_test/app:/app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    mem_limit: 1g
    restart: always

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

